//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Opgave7EF
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class EksamensopgaveDBReneEntities : DbContext
    {
        public EksamensopgaveDBReneEntities()
            : base("name=EksamensopgaveDBReneEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Booking> Bookings { get; set; }
        public virtual DbSet<Bookudstyr> Bookudstyrs { get; set; }
        public virtual DbSet<Kategori> Kategoris { get; set; }
        public virtual DbSet<Lejer> Lejers { get; set; }
        public virtual DbSet<Udstyr> Udstyrs { get; set; }
        public virtual DbSet<Virksomhed> Virksomheds { get; set; }
    }
}
