//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Opgave7EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bookudstyr
    {
        public int id { get; set; }
        public int antal { get; set; }
        public Nullable<int> bookingId { get; set; }
        public Nullable<int> udstyrId { get; set; }
    
        public virtual Booking Booking { get; set; }
        public virtual Udstyr Udstyr { get; set; }
    }
}
