//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Opgave7EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Udstyr
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Udstyr()
        {
            this.Bookudstyrs = new HashSet<Bookudstyr>();
        }
    
        public int id { get; set; }
        public string navn { get; set; }
        public string beskrivelse { get; set; }
        public decimal dagspris { get; set; }
        public decimal forsikringspris { get; set; }
        public int antal { get; set; }
        public Nullable<int> virksomhedsId { get; set; }
        public Nullable<int> kategoriId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Bookudstyr> Bookudstyrs { get; set; }
        public virtual Kategori Kategori { get; set; }
        public virtual Virksomhed Virksomhed { get; set; }
    }
}
